AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "config.ru"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/20*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
