categories:
- Games children play outside
- Movies with aliens in
- Hamburger toppings
- Clothing items you can knit
- Easy school classes
- Supermodels
- The seven deadly sins
- Pets other than cats and dogs
- Things you can eat without teeth
- TV news presenters
- Legendary football/soccer players
- Disney princesses
- Reasons people get fired
- Rock bands older than 20 years
- Locations where rich people live
- Singers who have acted in films
- First date activities
- Countries in Asia
- Types of sandwiches
- Clothing brands
- Breeds of dog
- Supplies found in an emergency survival kit
- Types of tree
- Muppets
- Movies with multiple sequels
- Famous dogs
- Words on traffic signs
- Yoga poses
- Books that have been made into movies
- Rivers in the U.S.
- Rivers in the E.U.
- Things people do while talking on the phone
- Precious gemstones
- Types of tea
- Ways to stay cool on a hot day
- Movie theatre snacks
- Batman villains
- Things to bring on a road trip
- Mr. Potato Head parts
- Modes of transportation with wheels
- Corporate mascots
- Places you have to queue / wait in line
- Sports movies
- U.S. states beginning 'M' or 'N'
- Islands
- Makeup brands
